### ISSUE TITLE
Need an example

### ISSUE THREAD

**Issue by amigax** [moagrius/MapView#1]
Hey, this thing looks awesome but I need more info on how to use it!

In particular things I dont understand: 

mapView.addOnReadyRunnable(someRunnable);
mapView.addOnReadyRunnable(anotherRunnable);

What are these runables and why are they added?

mapView.setMapEventListener(someMapEventListener);

whats this an why is it added?

mapView.addZoomLevel(6180, 5072, "tiles/boston-1000-%col%_%row%.jpg","downsamples/boston-pedestrian.jpg", 256, 256);

what is the downsampled image all about? 

If you could provide a working sample of this in action I think it would be much nicer to understand.

Thanks ! Im hoping I can use this for my current app.

**Comment by amigax** [comment]
Ive set it up like this and theres no errors:

**Comment by amigax** [comment]
MapView mapView = new MapView(this);
 mapView.setBaseMapSize(512, 512);
 mapView.addZoomLevel(("tilesets/2048/%row%.%col%.png"));
 mapView.initialize();

Yet im just left with a white screen?

**Comment by moagrius** [comment]
The Runnables are entirely optional - their run() methods are called when the MapView (and it's children) have been laid out.  You can ignore them for now.

Downsamples are singe low-resolution images that are stretched to fill area beneath the tiles, to show an approximation of the tiled image while tiles are rendering.  They are optional.  I generally use a 500x500 jpeg, saved at a low quality (e.g. 3 in PhotoShop) for each zoom level.

An example Activity is here: https://github.com/moagrius/MapView/wiki/Example-Activity.

Not sure why it didn't render - did you add it to your contentview?  I'll download a fresh copy and try it using the parameters you've listed and post back.

**Comment by moagrius** [comment]
Hm...  Looks like perhaps one of the signatures is invalid, or it's dying on a null value for the downsample.  I'll investigate.  For now, I'm assuming that your tile size is 512, but your total map is not... perhaps it's 2048x2048?  If so, try this:

```
MapView mapView = new MapView(this);
mapView.addZoomLevel(2048, 2048, "tilesets/2048/%row%.%col%.png", "path/to/any/image/base.png", 512, 512);
mapView.initialize();
```

Apparently the different signatures aren't ready for primetime - I'll update the readme to reflect that.

**Comment by amigax** [comment]
Hey thanks for the quick reply, I have it working much better now the main issue is it keeps crashing with out of memory errors, here is my set up:

 MapView mapView = new MapView(this);
mapView.setTileTransitionDuration(100);
mapView.addZoomLevel(7680, 4096, "tilesets/128/%col%.%row%.png", "downsamples/128_50percent.jpg",  512, 512);
mapView.addZoomLevel(4096, 2048, "tilesets/256/%col%.%row%.png", "downsamples/256_50percent.jpg",  512, 512);
mapView.addZoomLevel(2048, 1024, "tilesets/512/%col%.%row%.png", "downsamples/512_50percent.jpg",  512, 512);
mapView.addZoomLevel(1024, 512 , "tilesets/1024/%col%.%row%.png","downsamples/1024_50percent.jpg", 512, 512);
mapView.addZoomLevel(512 , 512 , "tilesets/2048/%col%.%row%.png","downsamples/2048.jpg", 512, 512);//same size..
mapView.initialize();
setContentView(mapView);

I think its my downsamples that are causing it ive made them very low quality jpegs the same size as the entire map, i will try the 500x500 thing you suggested although im not sure how/if it will scale perfectly to match the tiles ?

**Comment by amigax** [comment]
Sorry I meant 50% not the full size for my downsamples, I will reduce them to 25% and see what happens

**Comment by amigax** [comment]
Also if I play with it for a while I get this error FATAL EXCEPTION: main
java.lang.NullPointerException
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1372)
       at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
       at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
       at android.view.View.draw(View.java:6883)
       at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
       at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
       at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
       at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
       at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
       at android.view.View.draw(View.java:6883)
       at android.widget.FrameLayout.draw(FrameLayout.java:357)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1862)
       at android.view.ViewRoot.draw(ViewRoot.java:1522)
       at android.view.ViewRoot.performTraversals(ViewRoot.java:1258)
       at android.view.ViewRoot.handleMessage(ViewRoot.java:1859)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:130)
       at android.app.ActivityThread.main(ActivityThread.java:3683)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:507)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
       at dalvik.system.NativeStart.main(Native Method)
   Force finishing activity thrillseeker.app.paultons/.activities.ScrollingMapActivity

**Comment by moagrius** [comment]
Yes they'll scale to fit...  I generally use downsamples about 500 pixels.  You can also use a single downsample for all the zoom levels (assuming the details aren't that different) which will save memory.  Also disabling tile transitions will help with bitmap memory (since the tiles are destroyed immediately, whereas with the transition they are destroyed after the animation completes).  This can be accomplished with `setTileTransitionEnabled(false);` http://moagrius.github.com/MapView/documentation/reference/com/qozix/map/MapView.html#setTileTranstionEnabled(boolean)

Finally, I found the line that was causing null downsamples to fail - I had removed a null test before hiding the layer and forgot to replace it.  The issue was in https://github.com/moagrius/MapView/blob/master/com/qozix/map/layers/TileLayer.java, and is now corrected.  Overwrite this file and you'll be able to omit downsamples (I just tested with the minimal setup referenced in your comment here https://github.com/moagrius/MapView/issues/1#issuecomment-9322579 and it worked).

**Comment by moagrius** [comment]
Gah - I just got the same error - looks like I need to roll back some of the updates and do some more thorough debugging.  Sorry about that - I'll try to get something up in the next few days.

**Comment by moagrius** [comment]
OK...  that one was because we weren't posting to the UI thread after the tile transition was complete, and trying to do UI work in another thread.  That's been updated (same file, TileLayer.java) - you can try it again now, or feel free to wait until I've had a chance to go through everything and perform a few rounds of thorough debug.

**Comment by amigax** [comment]
Thanks ever so much for this, this is the 3rd or 4th attempt ive made to make this kind of map work and this is definitely the most promising one so far, I will try the new TileLayer.java and let you know whats happening. One thing I did notice is that on some zoom levels I cant pan properly right to the bottom either, or maybe I did something wrong.

**Comment by moagrius** [comment]
Sure, no problem.  Not sure why the zoom levels aren't panning correctly - as I mentioned, I'll spend some serious time on it whenever I get a breather from "real" work and try to fix it up (hopefully within the next week).  The one bit of good news I can give you is that the original version of this (not published) does "work", and has been used by thousands of devices in 5 apps on google play, but those were very rough, hacky versions for my own use, and without a decent external API - my goal was to convert those to a single generic public component as a "black box" - which is where things went wonky...  it's obvious I just missed (quite a bit) when converting it to a library.

**Comment by amigax** [comment]
That is great news, this will be used in a few very popular apps once we are all good (I can tell you which apps in private) - I can imagine making it standalone has caused some issues, if it helps I can send my tileset and activity to aid your testing?

**Comment by amigax** [comment]
Yeh theres definitely some sort of bug in the zoom, after a zoom it sort of jumps to the top left tile, and then youre stuck there.. if you give me your email I can send you these tiles maybe theres some issue they can help with.

**Comment by moagrius** [comment]
Definitely having another tile set to debug with would be good - I'll IM you with my email.

**Comment by amigax** [comment]
Cheers, the only issues I can still see are:
- sometimes (not too often) a tile simply wont update (white square or a square form the downsampled one).. presumably this is probably an out of memory issue and since im using an old nexus one it prob wont show up on newer devices anyway
- the zooming seems to work fine until you get to the absolute max zoom then it jumps to the top left tile, the markers retain the position they had before but seeing as its on the top left tile and not the previous one it looks like its in the wrong position now. And at this point I cant seem to scroll down any further, even though I should be able to

I will send over my tiles when I get the IM, cheers, this is a great project and im happy to find it :-)

**Comment by moagrius** [comment]
Cool - glad to have another dev for debugging.  I sent an email to the address listed in your profile.  Thanks for the help!

**Comment by amigax** [comment]
any updates? :)

**Comment by moagrius** [comment]
took a quick look but won't be in deep until Monday and Tuesday nights - hoping to post a new revision Wednesday.

**Comment by moagrius** [comment]
I see it's been 5 months since I last commented, but I finally got the major rewrite done and committed.  The readme has some highlights and the docs have been updated.  This version does "work" - I've tested in limited forms on several devices and the most common API at least is much more stable in this version.

**Comment by Shusshu** [comment]
When you do the sample app, you will need me to create some pom.xml for maven.

I suggest to follow a multi module structure.

the lib jar classes in a folder and the sample in another one:

root\mapview-lib
root\mapview-sample

I would put the current content of the repository inside mapview-lib
and create 2 pom: 1 for the root and 1 for root\mapview-sample

**Comment by moagrius** [comment]
I think I'll put the sample in it's own repo - anything special I need to do in that case.

I got NDA sign-off, but am waiting on a un-branded tile set from my agency to to create the sample.

**Comment by moagrius** [comment]
6 months later - I have a working sample:

Source: https://github.com/moagrius/MapViewDemo
Compiled: http://moagrius.github.io/MapView/MapViewDemo.apk

**Comment by jolenwood** [comment]
I run your example, found addmarker click event problem, on the emulator available, on a real machine can not use, the simulator click with the mouse is a point, but click on the finger on the real machine onis no longer a point, as if there will be a conflict, how to solve this, you have not come across?

**Comment by moagrius** [comment]
Hi - I'm not real clear on the issue you're describing - could you provide details?  I'll try to check the sample on a broader range of devices to see if I can spot any obvious issues.

**Comment by jolenwood** [comment]
First of all thank you very much to reply to me, I specifically describe the problems I encountered, I hope you can understand.I downloaded your example, imported my work space.When I run on the test machine, I click on the mark has no effect.My test machine model is sammsung YP-GI1, and system version Android2.3.6. I print the log in the OnClickListnter() ,but no log.But when I run in the simulator, there is no such a problem.So I guess, when running on the emulator, click on the event through the mouse click is just a point, there is no other touch events.But on the test machine, finger click a region, with the drag of the map will zoom function conflict?The I test machine above, as much as possible to keep the vertical Click guarantee not to drag the map, that's when I discovered there was the effect that can pop Callout!But doing so is very difficult, so I hope you can help me solve this problem.Thank you so much with such a good mapview, thank you!I hope you can reply to my question.

------------------ 原始邮件 ------------------
发件人: "moagrius"notifications@github.com;
发送时间: 2013年4月23日(星期二) 凌晨2:29
收件人: "moagrius/MapView"MapView@noreply.github.com; 
抄送: "jolenwood"443564200@qq.com; 
主题: Re: [MapView] Need an example (#1)

Hi - I'm not real clear on the issue you're describing - could you provide details?  I'll try to check the sample on a broader range of devices to see if I can spot any obvious issues.

**Comment by moagrius** [comment]
Hmm...  I just tried a fresh download on a couple different devices and no problems...  Try removing the the line `mapView.setShouldIntercept( true );` and see if that helps.

**Comment by jolenwood** [comment]
Thank you so much!Removing the the line mapView.setShouldIntercept( true ); it works！Thank you! 

------------------ 原始邮件 ------------------
发件人: "moagrius"notifications@github.com;
发送时间: 2013年4月23日(星期二) 上午10:00
收件人: "moagrius/MapView"MapView@noreply.github.com; 
抄送: "jolenwood"443564200@qq.com; 
主题: Re: [MapView] Need an example (#1)

Hmm...  I just tried a fresh download on a couple different devices and no problems...  Try removing the the line mapView.setShouldIntercept( true ); and see if that helps.

**Comment by moagrius** [comment]
no problem.  i've heard that intercept is buggy on certain installs, but haven't experienced it myself.  good luck!

**Comment by jolenwood** [comment]
<com.qozix.mapview.MapView
        android:id="@+id/mapview"
        android:layout_below="@id/a_title" 
        android:layout_width="fill_parent"
        android:layout_height="fill_parent">
    </com.qozix.mapview.MapView>

mapView=(MapView)findViewById(R.id.mapview);

I just want to use mapview in xml,but it do not works! what shoud I do?Please help me!

------------------ 原始邮件 ------------------
发件人: "moagrius"notifications@github.com;
发送时间: 2013年4月23日(星期二) 上午10:46
收件人: "moagrius/MapView"MapView@noreply.github.com; 
抄送: "jolenwood"443564200@qq.com; 
主题: Re: [MapView] Need an example (#1)

no problem.  i've heard that intercept is buggy on certain installs, but haven't experienced it myself.  good luck!

**Comment by moagrius** [comment]
i never bothered to support XML inflation.  you could probably extend (or hack) it do so pretty easily, but it's not really necessary - you can instantiate it with Java and use addView.
