### ISSUE TITLE
onInterceptTouchEvent

### ISSUE THREAD

**Issue by Shusshu** [moagrius/MapView#10]
The behavior before was better as it was easy to press on a point and get a popup or an action.
now the map moves on touch instead of getting to the point

**Comment by marcinkolonko** [comment]
that's not exactly true. right now it's only a drag, when the distance is greater then MapView.SINGLE_TAP_DISTANCE_THRESHOLD - if it's less then that, it's considered a tap.

**Comment by Shusshu** [comment]
Then how come I'm having a lot of trouble tapping on a marker

**Comment by marcinkolonko** [comment]
i don't know what your markers look like, and if you set a custom layout. see my issue #12

**Comment by Shusshu** [comment]
That's sounds interesting, I will look more into it

I did more testing and actually the touch event works well but you need to press above the marker

it's a normal behaviour in android the touch always need to be exactly on the button.

Humans tends to press below the element they are seeing.

In iOS you need to press below the element you touch in other words you need to keep the element in the line of sight.

**Comment by moagrius** [comment]
If you prefer to have it not intercept, you could extend it and just override onInterceptTouchEvent to return false...

<pre>public class MyMapView extends MapView {
public MyMapView(Context c){
  super(c);
}
@Override
public boolean onInterceptTouchEvent (MotionEvent event) {
  return false;
}
}</pre>

We could add this as a settable property possibly...

**Comment by Shusshu** [comment]
Yes that works well using the lib as a jar
I'll use MyViewMap until there is a better solution

**Comment by moagrius** [comment]
Since I suspect the onInterceptTouchEvent is causing 3 of the currently open issues, I'm definitely going to add a method to turn this on or off (and probably default to off), as soon as I get a moment.  I'll leave this issue open until I've done so.  Thanks!

**Comment by moagrius** [comment]
this is now off by default, but can be enabled with `setCacheEnabled(boolean)`
