### ISSUE TITLE
onConfigChange (phone rotation) - moveToAndCenter bug

### ISSUE THREAD

**Issue by Shusshu** [moagrius/MapView#11]
When I rotate the phone and call moveToAndCenter it goes in the wrong place

**Comment by moagrius** [comment]
GTK.  using coordinates, or pixels, or either?

**Comment by Shusshu** [comment]
using coordinates, but i'll test a bit more

EDIT:
Ok It was because I had a mistake with my scale. i was setting the wrong value in onRestoreState...
mapView.slideToAndCenter(point.getX() \* scale, point.getY() \* scale);
