### ISSUE TITLE
marker issue

### ISSUE THREAD

**Issue by marcinkolonko** [moagrius/MapView#12]
i manage the layout of my markers inside the marker, since they are a little complex.

so i had to set set `AnchorLayout.setClipChildren(false)`.
the problem is, when a childview in my marker is positioned outside the bounds of the marker, it isn't clickable anymore.

this behavior changed since the prvious version. any idea why?

i attached a image to illustrate it: the dark rectangle shows the bounds of my marker. the pin is a child of marker, the green and red dots are only to show where i click.
when i click the green touchpoint the click is registred, the click on the red point does nothing.
![Screenshot_2013-03-12-14-10-32](https://f.cloud.github.com/assets/340690/248600/a5069750-8b16-11e2-99bb-cfc1299d2975.gif)

**Comment by moagrius** [comment]
very interesting...  I didn't do a lot differently with Markers - in fact I don't do much to them at all since I knew there were likely to be lots of different setups.

the big change was the onInterceptTouchEvent - try the workaround in #10 to see if that fixes it.

i'll add a todo to have the onInterceptTouchEvent behavior settable.

**Comment by marcinkolonko** [comment]
i doubt it has anything to do with events since it does work when the click happens inside view bounds

**Comment by moagrius** [comment]
I'll run some tests as soon as I get a minute and post back.  In the meantime, would you mind having onInterceptTouchEvent return false as decribed in #10 and see if it helps?  You might be right and it's totally unrelated, but if you can easily test it could be helpful.  Thanks.

**Comment by marcinkolonko** [comment]
your right. i forgot to overwrite my `View.onMeasure()` method. to reflect changed width/height after showing textbox.
now it looks like in the screenshot. it's hack, doesn't look nice, but without setting background on the marker, it's ok.
![Screenshot](https://f.cloud.github.com/assets/340690/258261/33e765a6-8c90-11e2-95fd-8145f950aa6e.png)

**Comment by moagrius** [comment]
any suggested changes to the lib to accomodate for this?

**Comment by marcinkolonko** [comment]
i don't think a change is needed since it's working as expected. i would like to have a possibility to add xOffset and yOffset (in pixel) though.

like: in `FixedLayout.LayoutParams` added two properties. `LayoutParams.xOffset` and  `LayoutParams.yOffset`
then consider them in `ViewGroup.onLayout()`

so if you look at the image above, l would set marker anchor to bottomleft and use xOffset to finetune the position of the marker.

**Comment by moagrius** [comment]
That might be OK for TranslationLayout.  I'll leave this open for now but it sounds reasonable at the moment.  I hope to do a big update next weekend.

Thanks for all the feedback.  If your app's not under NDA and you'd like to share the link, I'd be interested in taking a look (and possibly linking to it in the the readme)
