### ISSUE TITLE
slideToAndCenter - map does not refresh

### ISSUE THREAD

**Issue by Shusshu** [moagrius/MapView#19]
If  we slide to a location which was not loaded the tile never loads

**Comment by LucasDeVil** [comment]
I'd like to kinda reopen it since it seems to work only when the process of tile drawing is not completed. As soon as all visible tiles are drawn the slideToAndCenter() doesn't work anymore. It will be performed as soon as the map tiles should be redrawn again, i.e. dropping or creating a marker.

**Comment by moagrius** [comment]
@LucasDeVil can you create a new issue with exact steps needed to recreate?  i'm hoping to do an update mid June.
