### ISSUE TITLE
Map Landscape (Rotation)

### ISSUE THREAD

**Issue by Shusshu** [moagrius/MapView#23]
The map does not load completely on the far right in the furthest zoom level

I got 2 cases for this:

If I'm zoomed in and go to far right the map loads then I zoom out completely  the right part of the map never loads and we see white imgs.

On the other hand if I am zoomed in the centre of the map and zoom out completely the map is smaller than it should it does not show the white imgs and never load them

This only happens in landscape

**Comment by moagrius** [comment]
good feedback.  my guess is that a solid teardown method will fix this, but i'm going to keep it open and as a separate issue because i'm not sure - will test as soon as possible.

**Comment by moagrius** [comment]
I've added new methods to help manage state - `clear` and `destroy`.  My (admittedly limited) tests show that when implementing destroy in `onDestroy` and `clear` in `onPause` (along with a `requestRender` in `onResume`), everything appears to be behaving normally.  I'd be interested to hear back on this one and am leaving it open for now.

**Comment by Shusshu** [comment]
Not sure if the 1.0.1 fixed this or the following 2 lines : 
mapView.setScaleToFit(false);
mapView.setScaleLimits(0.25, 1.0);

**Comment by moagrius** [comment]
closing per fix referenced in #21
