### ISSUE TITLE
Huge map loading time

### ISSUE THREAD

**Issue by frankowskid** [moagrius/MapView#24]
I have a map which is 150x150 tiles. I takes over 15 secs to create list of MapTiles in TilesLayer - update. 
While zooming previous maplevel level is removed from the view and screen is gray while new level is loading.

**Comment by moagrius** [comment]
In theory, you could have any number of tiles - it only considers those that should be showing on screen at any time, so the load time you're describing seems to mean there's a problem.  It's important to provide the smallest possible tile set that might be displayed.

Can you share the relevant code, as well as tile and map sizes for each tile set?

**Comment by frankowskid** [comment]
Sorry for the inconvenience - I've been using very old code :]

**Comment by moagrius** [comment]
np - thanks for the feedback
