### ISSUE TITLE
setZoom does nothing in the UI

### ISSUE THREAD

**Issue by Shusshu** [moagrius/MapView#25]
Maybe it needs a refresh ?

I guess it is telling the system it needs to take imgs from that zoom level and that's it?

**Comment by moagrius** [comment]
this is the last-minute addition i referenced.  this method should just calculate the scale needed at the top of that zoom level and call setScale.  I haven't debugged it at all yet, but will as soon as I can.

**Comment by moagrius** [comment]
I'm considering removing this method, and just controlling scale directly - what do you think?  Is it likely to be useful?

**Comment by Shusshu** [comment]
Yup I think it's not needed if it's simply managing the scale

Benoit Billington

**Comment by moagrius** [comment]
cool, thanks
