### ISSUE TITLE
Mismatch between x & y values

### ISSUE THREAD

**Issue by phil-applegate** [moagrius/MapView#28]
It appears that in PathView.java the drawPath(List<Point> points) method has mistake regarding some x and y coordinates. 

The line (71) reads:
originalPath.moveTo( (float) start.x, (float) start.x );

I believe it should be:
originalPath.moveTo( (float) start.x, (float) start.y );

**Comment by moagrius** [comment]
Good catch, thanks.  I'll include in next update.
