### ISSUE TITLE
fatal exeption while registering geolocator

### ISSUE THREAD

**Issue by marcinkolonko** [moagrius/MapView#3]
i get this error when i try to register geolocator:

01-30 12:18:05.580: E/AndroidRuntime(4586): FATAL EXCEPTION: main
01-30 12:18:05.580: E/AndroidRuntime(4586): java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
01-30 12:18:05.580: E/AndroidRuntime(4586):     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
01-30 12:18:05.580: E/AndroidRuntime(4586):     at java.util.ArrayList.get(ArrayList.java:304)
01-30 12:18:05.580: E/AndroidRuntime(4586):     at com.qozix.map.zoom.ZoomManager.getZoomLevel(ZoomManager.java:92)
01-30 12:18:05.580: E/AndroidRuntime(4586):     at com.qozix.map.MapView.registerGeolocator(MapView.java:232)

do you have a idea how to make it work?

**Comment by Pycpik** [comment]
Hi,

You have to add zoom levels before registering your geolocator.

mMapView.addZoomLevel(4000, 4141, "sample_%col%_%row%.png", null, 256, 256);
...
mMapView.registerGeolocator(48.926795, 2.448872, 48.792626, 2.228886);

**Comment by moagrius** [comment]
Just FYI guys, this version is still very buggy and is not ready for release.  Forks welcome.

**Comment by marcinkolonko** [comment]
:) i know... but it's the only usable one... many thanks!
you have paypal? i would like to give you something back...

the geolocator worked perfektly. thanks!

**Comment by moagrius** [comment]
Thanks for the offer, but I'd rather have your help debugging in the future, if you're interested.

I have a "working" version that's in use on sevral public apps, but it's very hacky and ugly - the version here is the "cleaned up" version, with the flaw of it not working properly in all circumstances.

I have a project coming up in March that will use it, so will do a final refactor then - I'd love to have as many people debugging / crowdsourcing as possible.

**Comment by marcinkolonko** [comment]
I'd be glad if i could help. Even with my limited knowledge... I'm a long-time flash coder. Just started with android.

**Comment by moagrius** [comment]
awesome.  i'll post back here when ready.  thanks!
