### ISSUE TITLE
TileManager leaks on orientationchange

### ISSUE THREAD

**Issue by frankowskid** [moagrius/MapView#32]
TileManager will leak on orientation change.
The reason for memory leak is inner class of Handler instance. This should be static.

Example solution would be.

static private Handler handler = new Handler() {
        @Override
        public void handleMessage(final Message message)
        {
            switch ( message.what ) {
            case RENDER_FLAG :
                TileManager manager = (TileManager)message.obj;
                manager.renderTiles();
                break;
            }}};

```
public void requestRender() {
    // if we're requesting it, we must really want one
    renderIsCancelled = false;
    renderIsSuppressed = false;
    // if there's no data about the current zoom level, don't bother
    if ( zoomLevelToRender == null ) {
        return;
    }
    // throttle requests
    if ( handler.hasMessages( RENDER_FLAG ) ) {
        handler.removeMessages( RENDER_FLAG );
    }
    // give it enough buffer that (generally) successive calls will be captured
    Message message = handler.obtainMessage(RENDER_FLAG, this);
    handler.sendMessageDelayed(message, RENDER_BUFFER);
}
```

**Comment by moagrius** [comment]
Thanks for the post.  Orientation change has a bunch of problems #21, which also extends to anything that needs to deref or cleanup (onPause, onDestroy)  - I'm trying to get an update committed this week to start getting and handle on this.  I'll keep your patch handy.

**Comment by frankowskid** [comment]
another huge leak is made by inner class of RenderTask

**Comment by moagrius** [comment]
Thanks for the feedback.  I'm moving all the anonymous nested inner class Handlers away from that setup.  I know lint is reporting that warning.  I should have that done fairly soon.

**Comment by moagrius** [comment]
I've made an update with respect to the lint reports of potential leaks.
