### ISSUE TITLE
Changing ZoomLevels

### ISSUE THREAD

**Issue by phil-applegate** [moagrius/MapView#33]
Hi,

I'm looking to change the zoom levels used in the MapView throughout it's life. Do you know of a way of doing this?

I've added a couple of zoomlevels through the addZoomLevel method but I'd then like to remove all the zoom levels and add a new set pointing at a different set of tiles - what would be the best way of doing this? Currently I am creating a new MapView object each time the zoomlevels need to change.

Thanks

**Comment by moagrius** [comment]
I'm trying to get an update done in the next few days - it should be trivial to add a removeZoomLevel method - in theory you should be able to add and remove levels at any point during runtime, but I've never tested it.  I'd be curious to know how it works out.  I'll post an update to this thread when I've had a chance to commit the next round of changes.  Thanks.

**Comment by moagrius** [comment]
I've added a method `resetZoomLevels`.  LMK if this works for you.

**Comment by phil-applegate** [comment]
Yep, that's working great - thanks!
