### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mohlendo** [moagrius/MapView#38]
Would it be possible to change the license to a more common OS license like Apache License 2.0 or any other of the list http://opensource.org/licenses?
I would like to use the MapView in a commercial project and I don't know what the implications of the CCPL license are.

**Comment by moagrius** [comment]
The CC Attribution license just means that you have to link up the original author (this repo) somewhere (a comment at the top of MapView.java is fine, or whereever you prefer).  From their own summary:

> This license lets others distribute, remix, tweak, and build upon your work, even commercially, as long as they credit you for the original creation. This is the most accommodating of licenses offered. Recommended for maximum dissemination and use of licensed materials.

**Comment by moagrius** [comment]
i'm going to go ahead and close this issue - i like the attribution license generally, but if it's not sufficient for your set up i'd be happy to give you a waiver in writing.  post back if so.
