### ISSUE TITLE
intercepting gestures in mapview/touchlayer

### ISSUE THREAD

**Issue by marcinkolonko** [moagrius/MapView#4]
would you mind helping me with another issue?

my markers/overlays (RelativeLayout) have an onclick listener on a child (ImageView) inside.
when i try to drag the map, and the finger is on a marker, the marker consumes the event and doesn't pass it to the map.

as far as i understand it, i have two options:

1) stop event propagation in TouchLayer
2) intercept event in my marker.

what do you think?

**Comment by moagrius** [comment]
Event management in the Android FW can be tricky.  In general I think that #1 wouldn't work because the marker layer is inside the touch layer, so by the time the event got to the touch layer, stopping it wouldn't be helpful.  I'd probably try to override the marker's onTouch and make sure to return false (meaning "event should not be consumed") - however this means that you have to use a DOWN action (rather than a "click" - click fires when the finger goes back up, and if DOWN returns false, the UP will never happen, so consequently the click never gets called.  That means you wouldn't be able to use the standard event listeners - you'd have to fire your callback from within the overriden onTouch.

Alternatively you could try explicitly passing the event from the marker directly to the touchlayer touchLayerReference.onTouch(event) - I've had to do that in the past for a particularly crazy layout - it worked but was a pain to maintain.

HTH - LMK how it goes.

**Comment by marcinkolonko** [comment]
it can be tricky, indeed.

but when the maker layer is inside the touchlayer, the touch layer can intercept the touchevent. right? so in the intercept method i check for a gesture and if there's none, i could return false, and if user ist zooming or scrolling return true.

this is the definition of the onInterceptTouchEvent() method:

_The onInterceptTouchEvent() method is called whenever a touch event is detected on the surface of a ViewGroup, including on the surface of its children. If onInterceptTouchEvent() returns true, the MotionEvent is intercepted, meaning it will be not be passed on to the child, but rather to the onTouchEvent() method of the parent._

isn't it exactly what would be needed? or do i miss something?

**Comment by marcinkolonko** [comment]
no, that can't work. i see...

**Comment by marcinkolonko** [comment]
ok, i tested it out.

the _onInterceptTouchEvent()_ method should be the right one. i started with a simple one:

```
    @Override
    public boolean onInterceptTouchEvent(MotionEvent e)
    {
        final int action = e.getAction();

        switch(action){
            case MotionEvent.ACTION_MOVE:
                return true;
        }

        return false;
    }
```

and now i can scroll the map, even if i started the gesture on a marker.

**Comment by marcinkolonko** [comment]
so, i think i managed it - well actually a friend of mine in the end - to make it work quite elegantly:

```

    private boolean _consumed;
    @Override
    public boolean onInterceptTouchEvent(MotionEvent e)
    {
        final int action = e.getAction() & MotionEvent.ACTION_MASK;

        _consumed = false;
        if(action == MotionEvent.ACTION_MOVE){
            return true;
        }

        onTouchEvent(e);
        _consumed = true;

        return super.onInterceptTouchEvent(e);
    }
```

and in the onTouchEvent():

```
    @Override
    public boolean onTouchEvent(MotionEvent e) {

        if(_consumed){
            _consumed = false;
            return true;
        }
                ...........
                existing code
```

this affects only the TouchLayer.java

**Comment by moagrius** [comment]
Very cool - glad you got it working.  I'll try to incorporate this in the update I'm hoping to do this spring.

**Comment by Shusshu** [comment]
With the code you posted the onClickListener of the marker doesn't always receive the event which is problematic as it does not show the popup balloon in my case.
I'll dig a bit more

**Comment by marcinkolonko** [comment]
Hmm, can't confirm... Every marker always shows the textviev in my project. 

This is a weird one...

**Comment by marcinkolonko** [comment]
now i noticed as well... as of now i have no idea why...

**Comment by moagrius** [comment]
I've gone over this quite a bit - and had to deal with this on another component ( a fancier SlidingDrawer), and the lack of proper event bubbling and event target registration makes this tough.

My intention at this point is to intercept and reroute events through the touchlayer, and pass them manually to each marker or callout.  Hoping to get started on the rewrite late next month (March).

I have a general idea how to approach this, but welcome suggestions as well.

**Comment by moagrius** [comment]
@marcinkolonko The new version (just committed) handles move events for you - markers should no longer prevent scrolling.  The readme has some other info as well, and the docs have been updated.  It's a much more stable component now (I've personally tested the most common APIs on several devices).
