### ISSUE TITLE
Project Rename

### ISSUE THREAD

**Issue by moagrius** [moagrius/MapView#42]
I feel like the name "MapView" is too ambiguous, not really accurate (the widget could be used for many non-map type apps), and is confusing when considering the very common and popular google maps MapView.

I'm considering renaming the project to "TiledLayer".  Obviously the package and class names would be updated to reflect the new project name.

I'm posting this as an "issue" for any input one way or the other - does anyone have a problem with this, or opinion either way?

Thanks.

**Comment by mohlendo** [comment]
+1

**Comment by Shusshu** [comment]
I agree, MapView is confusing, TiledLayer is better but is it the best?

TiledImageView ?

**Comment by moagrius** [comment]
I was just thinking TiledLayer because of iOS's CATiledLayer, but it's certainly not a direct match to that component.

TiledImageView is a possibility.

Maybe just TiledView (or TiledView, or TilingView)?  TiledWidget?  TiledScrollView?

**Comment by frankowskid** [comment]
MapView is on each platform.
Additionally:
iOS uses CATiledLayer
WindowsPhone have MultiScaleImage and DeepZoom

We could reinvent the wheel and have something different for Android  ;)

TiledLayer +1

**Comment by Shusshu** [comment]
TiledView or TiledImageView as it sounds more android like

**Comment by moagrius** [comment]
> We could reinvent the wheel and have something different for Android ;)

I think that's appropriate - Android FW seems to like being different :)

> TiledView or TiledImageView as it sounds more android like

I agree.  TiledView +1

**Comment by moagrius** [comment]
TiledView it is.  Thanks for the input everyone.  I'll hold off on the rename until another large update justifies it.
