### ISSUE TITLE
Extra zoom feature

### ISSUE THREAD

**Issue by frankowskid** [moagrius/MapView#48]
Would it be possible to implement possibility to zoom over the maxzoom. I would mean to go with scale over 1.0 for max zoom. The reason is that on Galaxy S4, which has FullHD display, the pixels are very small and max zoom doesn't seem to be enough.

**Comment by moagrius** [comment]
`setScaleLimits` will allow zoom greater than 1, but I can't say I've tested it thoroughly.

**Comment by moagrius** [comment]
@frankowskid did this work for you?  can I close this issue, or is anything else required?

**Comment by frankowskid** [comment]
Sorry for late replay.
 I've also haven;t tested it thoroughly. 
The zoom itself seems to work but the map center point is not maintained.
I look like the right edge of a map is frozen an all the content is pushed to the left side.

**Comment by moagrius** [comment]
I'm not surprised - it was never intended to show any image greater than 100%, or less than 50%, and presumed new zoom levels would be used for a max value.  That said, it probably would be pretty easy to get the bounds to update appropriate - I'll try to get this added for the next updated.  Thanks for the feedback.

**Comment by frankowskid** [comment]
The reason I've requested this feature is that on new Galaxy S4 native resolution is too small to see details on the image.

**Comment by Shusshu** [comment]
What's the size of the img ?

**Comment by moagrius** [comment]
I looked into this and it's not a quick fix, but I do think it's a valuable feature.  With the project rename, and some other API-breaking changes I'd like to implement, I'm going to close this for now and add it to a new feature list for the major upgrade ("TileView").

**Comment by moagrius** [comment]
[TileView](https://github.com/moagrius/TileView) is now available, and supports max scale greater than 1
