### ISSUE TITLE
Increase the scrollable area in order to scroll the edges of the map into view

### ISSUE THREAD

**Issue by mohlendo** [moagrius/MapView#49]
Another crazy feature request:

I would like to be able to scroll to the edges of the map. Right now the MapView only allows to scroll until the edge of the map is reached. But I would like to scroll further - until the edge of the map is in the center of the screen.

**Comment by moagrius** [comment]
You'd have to hack it for that - the relevant bits are in the super class `ZoomPanLayout` - you could probably mess with (constrainPoint)[https://github.com/moagrius/MapView/blob/master/src/com/qozix/layouts/ZoomPanLayout.java#L494] to modify the scroll limits - you might need to set the map width and height as well, but probably not.

HTH

**Comment by mohlendo** [comment]
Ok, thanks! I will give it a try!

**Comment by mohlendo** [comment]
It works. Thanks again! Here is the commit: a7916e0f3d1497263428e8f787cef0576424851a

**Comment by moagrius** [comment]
Awesome - gj.
