### ISSUE TITLE
refactor as an Android library

### ISSUE THREAD

**Issue by Shusshu** [moagrius/MapView#5]
Hi,

Would you mind if I refactor this project in order to be structured as an Android library ? 

And also if I would mavenise it ?

**Comment by moagrius** [comment]
Feel free.  Just FYI, this version has some major bugs - enough that I would not use it in production code.  I have a project that'll be using it due in March, so my plan (tentatively) at this point is to do a major rewrite then and bring it up to working condition (I do have working versions, but they're all very hacky and very tightly coupled to the projects their used in).

**Comment by Shusshu** [comment]
Ok good to know,

I also have a product due late march that needs this kind of view and this was the best project out there.

What are the major bugs? maybe we can work together rewriting your lib.

**Comment by moagrius** [comment]
The first Issue thread describes some: https://github.com/moagrius/MapView/issues/1

I have to say that I've only used this version for a couple very quick tests, and not in "live" projects.

The short story is that I've used a version of this component in several projects, but all were hacky, inelegant and tightly coupled to the specific project codebase.  I started rewriting it to be more of a black-box when publishing this version, but haven't had time to give it as much attention as I'd like.

Anything you'd like to contribute would be greatly appreciated.

Thanks.

**Comment by moagrius** [comment]
Just a heads-up - I've just committed the rewrite I'd mentioned.  It's quite a bit different - the readme lists some highlights, and the docs are updated.  I've tested this version in a limited form on several devices, and this one "works" and is a _lot_ more solid and stable, but I haven't had time to test some of the API, or things like manipulating it via direct method calls from a set of controls, for example.  I do need to put together a sample app and a jar pretty soon (working on getting NDA settled).  Feel free to mavenize - in fact anything you'd like to contribute (debug, code review, etc) would be more than welcome.  Thanks.

**Comment by Shusshu** [comment]
Great I will test and mavenise on Tuesday

**Comment by moagrius** [comment]
Awesome - thanks.

**Comment by Shusshu** [comment]
Done
