### ISSUE TITLE
Loading downsample via TileDecoder 

### ISSUE THREAD

**Issue by tinkerlog** [moagrius/MapView#53]
Hi there,

first, thanks! Great component.

I wrote a TileDecoder to load tiles from the file system, as our map gets downloaded and stored locally. 
It would be cool, if the downsample could be loaded through the same method as the tiles.

Cheers,
Alex

**Comment by moagrius** [comment]
Yes, I hope to include that next update - hopefully within the next week or two.  The custom decoders were a relatively late add, so still needs some fine tuning (including downsample decoding, as you mentioned).  Issue also discussed #46 

Thanks for the feedback.

**Comment by moagrius** [comment]
This has been included and will be available in the next minor update.  Thanks.
