### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by moagrius** [moagrius/MapView#57]
There are a number of API-breaking changes I'd like to make, as well as the project rename discussed earlier, which will effectively require a new repo.  I'll continue to maintain this repo for a while, with the goal of eventually moving everything over to TileView.

Please use this thread for any feature requests or enhancements, even if they'd break the existing API.  Thanks.

**Comment by moagrius** [comment]
Allow max scale greater than 1.0.

**Comment by moagrius** [comment]
Revisit path drawing strategy to write to a single canvas.  Expose more of the path drawing API.  Remove PathView.

**Comment by moagrius** [comment]
Revisit HotSpot strategy and API.  Implement Polygons as the default #47, revisit user event strategy #51

**Comment by moagrius** [comment]
Allow custom decoders for both tiles and downsamples.  Revisit implementations.

**Comment by moagrius** [comment]
Manage marker events out of the normal event flow, so consumption/interception can be managed reliably.

**Comment by moagrius** [comment]
Add "setAllowScale" method.  Improve min/max scale management (min scale should work predictably, max scale should go beyond 1.0f, min should supercede max).

**Comment by moagrius** [comment]
Implement tile fade transitions (again).

**Comment by moagrius** [comment]
Move + scale to absolute rectangle #58

**Comment by moagrius** [comment]
allow custom tile name pattern parser

**Comment by LucasDeVil** [comment]
Hey, I'm interested putting the work forward. Is there a way to contact you besides github?

**Comment by moagrius** [comment]
Hi all.  TileView is up: https://github.com/moagrius/TileView.  I'll be deprecating MapView eventually, and any future work will be on TileView.  If anyone wants to pick up MapView on their own, LMK, but I don't think it's necessary - TileView can do everything MapView does, and more.

Thanks to everyone who contributed - the final release was light years better than the initial commit.

**Comment by snacky6** [comment]
Hey ! I use your widget in my app and I'm interested in inserting a grid. I already use HotSpots but I would like to have a visual grid ! Is there a way I can contact you ?

**Comment by moagrius** [comment]
Not sure what you mean by "inserting a grid", but you can use this form to get in touch: http://qozix.com/contact

**Comment by snacky6** [comment]
I need to draw a grid on my map that can be shown/hidden. This way I can see areas I've added with HotSpots! I've tried to do it by adding a canvas but it didn't work...

**Comment by moagrius** [comment]
I see.  If you have specific questions, feel free to open a new issue.  If you need something out of context or beyond scope, you can use the contact form I linked above.

Thanks,
