### ISSUE TITLE
moveTo/slideTo rectangle

### ISSUE THREAD

**Issue by cjbraden** [moagrius/MapView#58]
It would be nice to move/slide to a rectangle and have the zoom level set appropriately

**Comment by moagrius** [comment]
Not sure what you mean?

**Comment by cjbraden** [comment]
Sorry, I thought this was going to show up under feature requests, and to be a little more clear, it would be nice to have a mapView function similar to moveToAndCenter or slideToAndCenter where you pass it a top left/bottom right or Rectangle object, (either image coords or geo coords) and it will move and zoom you to a best fit of that rectangle. Technically, it's possible now by figuring out the scale factor difference between my rectangle and the overall size of the map, then setting the zoom factor, but it might be nice to have built in support.

**Comment by moagrius** [comment]
I see - yes, I've been asked about that before.  I've added it to the feature list - thanks for your input.

**Comment by moagrius** [comment]
This has been implemented in TileView (https://github.com/moagrius/TileView)... Although I actually added it to ZoomPanLayout (it's inherited by TileView, of course).
