### ISSUE TITLE
slideToAndCenter randomly not works

### ISSUE THREAD

**Issue by LucasDeVil** [moagrius/MapView#59]
In addition to #19 und #20 I'd like to re-open this issue.

I'm working with the MapView in a fragment. When starting the map fragment MapView should slideToAndCenter to a given position. This always works well.

In addition I have a 'center' button which can be touched. In the buttons onClick Listener I do another slideToAndCenter.

This randomly works or fails.
When the Map is rendered and I touch the button nothing happens.
When the Map is still rendering (i.e. touching the button shortly after swiping on the map when some tiles aren't rendered yet) the map slides to the position.

**Comment by moagrius** [comment]
I'm pretty sure it's scaling the point twice.  It probably works fine when scale is 1, but that's it.

I'm fairly deep into TileView at the moment, but will try to find some time this week to commit a fix for this issue.  Actually, I have an local version with several fixes that I haven't committed - this one might already be done.

**Comment by moagrius** [comment]
I've just committed an update that should patch this - it seems fine on my local build (using coordinates).  This is not a solid rewrite, and the positioning scheme has become more complicated than it should be and it probably does need to be rewritten, but I'm concentrating on TileView now and this will likely be the last commit.  Feel free to commit patches on forks and I'll continue to review and (possibly) accept merge requests in the future.

**Comment by moagrius** [comment]
This should be fixed in TileView (https://github.com/moagrius/TileView)
