### ISSUE TITLE
Positioning of markers when zooming

### ISSUE THREAD

**Issue by jdegroot** [moagrius/MapView#6]
Hi,

My colleague and I have rewritten a bit of your code which places markers on the marker layer. We've adapted it so that the coordinates passed to addMarker(view, x, y) represent the center of where the view should be placed, instead of it being the top left corner. Also, we've adjusted the way the marker is placed when zooming the map so that the position of the marker remains the same (previously it was moving a little bit).

Please find the adapted code below (from TranslationLayer.java):

``` java
@Override
    protected void onLayout(boolean changed, int l, int t, int r, int b) {
        int count = getChildCount();
        for (int i = 0; i < count; i++) {
            View child = getChildAt(i);
            if (child.getVisibility() != GONE) {
                LayoutParams lp = (LayoutParams) child.getLayoutParams();
                int w = child.getMeasuredWidth();
                int h = child.getMeasuredHeight();
                int newL = lp.x - (w / 2);
                int newT = lp.y - (h / 2);
                int scaledX = (int) (0.5 + (newL * scale));
                int scaledY = (int) (0.5 + (newT * scale));
                int y = scaledY - (int) (h * (1 - scale));
                int x = scaledX - (int) ((w / 2) * (1 - scale));
                child.layout(x, y, x + w, y + h);
            }
        }
    }
```

Lastly, we've removed the part where the anchors were handled, since we couldn't figure out exactly what this was supposed to do. It seemed to me that it the previous code just moved the marker one image length to the left and one image height to the top if no anchors where set.

Hopefully this is helpful for a future release.

**Comment by moagrius** [comment]
Thanks for contributing, however the original version allows centering, or any other marker logic...  See http://moagrius.github.com/MapView/documentation/reference/com/qozix/map/MapView.html#setMarkerAnchorPoints(float, float)

Passing mapViewInstance.setMarkerAnchorPoints(0.5f, 0.5f) would center markers.

**Comment by jdegroot** [comment]
You are completely right. Now I understand what the anchor points are for. Thanks for explaining.

**Comment by moagrius** [comment]
No problem, thanks for contributing.

**Comment by moagrius** [comment]
Just a heads up - I just committed a very significant rewrite - it's a much more stable component now.  The readme lists some highlights and the docs have been updated.
