### ISSUE TITLE
Adding ZoomLevels dynamically does not allow zooming.

### ISSUE THREAD

**Issue by Swiftwork** [moagrius/MapView#60]
Adding ZoomLevels dynamically through buttons and spinners does not re-calculate the available scale, which in turn allows only panning and not zooming. The issue persists through resetZoomLevels() as well. An additional example is if a default map is loaded and then replaced with a smaller set of tiles, the mapview allows zooming beyond the limits of the new tileset.

I tried finding the cause, but had no luck. I believe that the issue might be that all layouting and drawing methods only happen once during runtime and changes made after do not re-calculate the scale.

Edit: Using setScaleToFit(true) causes the ZoomPanLayout to calculateMinimumScaleToFit() thereby allowing zoom again.

**Comment by moagrius** [comment]
The new API (TileView) has addressed this issue.  I hope to do an initial commit within the next month.
