### ISSUE TITLE
How to listen onLongPress event?

### ISSUE THREAD

**Issue by yolapop** [moagrius/MapView#61]

**Comment by moagrius** [comment]
of what?  a marker?  just like you would any View...

**Comment by yolapop** [comment]
No, on the map..

**Comment by moagrius** [comment]
There is no MapEventListener callback for a longpress, so you'd do so like you would any other ViewGroup (e.g., FrameLayout)...  You could assign a listener directly, but that'd probably consume it and break existing touch management, or you could override onTouch, etc.

**Comment by yolapop** [comment]
Alright thank you sir for the answer. I was actually looking for something like hotspot and just found it..

**Comment by moagrius** [comment]
No problem, glad you got it figured out.  Just FYI, this widget is going to be "superceded" by another in the next few weeks (hopefully), which (among other things) will have a more flexible hotspot system, so you may want to check back for that release.
