### ISSUE TITLE
redrawing map after moveToAndCenter()

### ISSUE THREAD

**Issue by marcinkolonko** [moagrius/MapView#7]
i noticed when using moveToAndCenter() the downsampled image stays visible and the map isn't redrawing.

you're aware of this? you have a tip on how to fix that?

**Comment by moagrius** [comment]
I was not aware, and am not sure how to fix it with that version -  maybe a call to invalidate, or perhaps the tilelayer needs to render(), or the tile set needs updated with confirmOrUpdateTileset().

that said, I have started the rewrite - it's a complete overhaul from scratch, and I expect it to be much more robust.  I'll try to keep the public API as close as possible, but the guts are being reworked from scratch - I've completed the zoom management and geolocation packages, and can tell you they're much better, but I don't have an ETA yet - hopefully within the next few weeks.

**Comment by marcinkolonko** [comment]
calling MapView.requestUpdate() in MapView.moveToAndCenter() did the trick

**Comment by moagrius** [comment]
cool - glad you got it worked out

**Comment by Shusshu** [comment]
yup that works !
