### ISSUE TITLE
add low res background image capability

### ISSUE THREAD

**Issue by jgastonraoul** [moagrius/MapView#9]
It would be a great idea to display a low res image background while tiles are loading in order not to loose a "visible reference".
It should work like the downsample in the previous version but with the same image for all zoom levels.

**Comment by moagrius** [comment]
sounds like I should probably put that back in.  I'll add it as a public method and let the dev worry about performance, next update.  For now, you can try the hack here:  https://github.com/moagrius/MapView/issues/8

**Comment by moagrius** [comment]
closing this as the task has been assigned to me in #14
